import Head from 'next/head';
import React from 'react'
import { Navbar } from '@ui';

interface Props {
  children: React.ReactNode;
}

export const RootLayout: React.FC<Props> = ({ children }) => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create-t3-app" />
        {/* <link rel="icon" href={svg.src} /> */}
        <title>Icon Generator AI</title>
      </Head>

      <div className='bg-slate-800 h-full text-white p-10'>
        <Navbar />
        <main className=' container m-auto'>
          {children}
        </main>
      </div>

      <footer>
        <div className="flex justify-between bg-gray-900 p-6 text-white">
          <p>© 2023 Seibert Software Solutions, LLC</p>
          <div className="flex gap-10">
            <p>Terms of Service</p>
            <p>Privacy Policy</p>
          </div>
        </div>
      </footer>
    </>
  )
}
