import { api } from '@/utils/api';
import Head from 'next/head';
import { useRouter } from 'next/router'
import React, { useEffect } from 'react'

const SuccessPage = () => {
  const router = useRouter();
  const sessionId = useRouter().query.session_id as string;

  const session = api.payment.getStripeSession.useQuery({ sessionId }, { enabled: router.isReady });

  useEffect(() => {
    /* eslint-disable */
    if (session.data) router.push('/collection');
    /* eslint-enable */
  }, [ session.data, router ]);

  return (
    <>
      <Head>
        <title>Success!</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel="icon" href="/public/favicon.ico" />
      </Head>

      <main className='flex min-h-screen flex-col items-center justify-center'>
        Validating payment...
      </main>
    </>
  )
}

export default SuccessPage